### ISSUE TITLE
something wrong

### ISSUE THREAD

**Issue by y-ken** [y-ken/mysql-udf-base64#1]
reported bug from user via mail.

> I looked at the code at: https://github.com/y-ken/mysql-udf-base64 and I see a bug.
> Try this and you will see it fails due to the encode / decode not working properly for all use cases:

``` sql
mysql> SELECT hex(compress('abc')) as one,         
hex(uncompress(compress('abc'))) as two,
hex(base64encode('abc')) as three,
hex(base64decode(base64encode('abc'))) as four,
hex(base64encode(compress('abc'))) as five,
hex(base64decode(base64encode(compress('abc')))) as six,
hex(uncompress(base64decode(base64encode(compress('abc'))))) as seven,
hex('abc') as eight\G
 
*************************** 1. row ***************************
  one: 03000000789C4B4C4A0600024D0127
  two: 616263
three: 59574A6A
four: 616263
five: 41774141414865635330784B426741435451456E
  six: 03000000779C4B4C4A0600024D0127
seven: NULL
eight: 616263
1 row in set, 1 warning (0.00 sec)
 
mysql> show warnings;
+---------+------+----------------------------+
| Level   | Code | Message                    |
+---------+------+----------------------------+
| Warning | 1259 | ZLIB: Input data corrupted |
+---------+------+----------------------------+
1 row in set (0.00 sec)
```

> Case Seven is Null, but is shouldn't be.  It's be cause case six's output doesn't match case one's output exactly.... but it should... 
> I believe the error may be caused by the usage of signed chars instead of unsigned ones based on the change made 10 months ago... but that is just a guess.

**Comment by y-ken** [comment]
When reverting https://github.com/y-ken/mysql-udf-base64/commit/f278437 commit, it shown the warning.

``` bash
$ gcc -Wall -fPIC -I/usr/local/include -shared base64.c -o base64.so
base64.c:104: warning: assignment from incompatible pointer type
base64.c: In function 'base64decode':
base64.c:214: warning: assignment from incompatible pointer type
```

Then, install it on MySQL 5.6.16 and execute query, it got crash by `mysqld got signal 11`.

## sample query

**actually**

``` sql
mysql> select base64encode('something');
ERROR 2013 (HY000): Lost connection to MySQL server during query
```

**expected**

``` sql
mysql> select base64encode('something');
+---------------------------+
| base64encode('something') |
+---------------------------+
| c29tZXRoaW5n              |
+---------------------------+
1 row in set (0.00 sec)
```

## The detail of error

```
$ sudo less /var/log/mysqld.log
Thread pointer: 0x1c931e0
Attempting backtrace. You can use the following information to find out
where mysqld died. If you see no messages after this, something went
terribly wrong...
stack_bottom = 7f6bd00fce18 thread_stack 0x40000
/usr/sbin/mysqld(my_print_stacktrace+0x35)[0x8d0f15]
/usr/sbin/mysqld(handle_fatal_signal+0x4a4)[0x65f9b4]
/lib64/libpthread.so.0[0x3cb620f500]
/usr/lib64/mysql/plugin/base64.so(base64encode+0x197)[0x7f6bb5f11962]
/usr/sbin/mysqld(_ZN11udf_handler7val_strEP6StringS1_+0x6e)[0x5f9ffe]
/usr/sbin/mysqld(_ZN17Item_func_udf_str7val_strEP6String+0x1c)[0x5fa0bc]
/usr/sbin/mysqld(_ZN4Item4sendEP8ProtocolP6String+0x41)[0x5afcc1]
/usr/sbin/mysqld(_ZN8Protocol19send_result_set_rowEP4ListI4ItemE+0xc7)[0x6593c7]
/usr/sbin/mysqld(_ZN11select_send9send_dataER4ListI4ItemE+0x67)[0x6a21d7]
/usr/sbin/mysqld(_ZN4JOIN4execEv+0x521)[0x6bb7d1]
/usr/sbin/mysqld(_Z12mysql_selectP3THDP10TABLE_LISTjR4ListI4ItemEPS4_P10SQL_I_ListI8st_orderESB_S7_yP13select_resultP18st_select_lex_unitP13st_select_lex+0x250)[0x6fdbc0]
/usr/sbin/mysqld(_Z13handle_selectP3THDP13select_resultm+0x187)[0x6fe447]
/usr/sbin/mysqld[0x6d905d]
/usr/sbin/mysqld(_Z21mysql_execute_commandP3THD+0x935)[0x6dada5]
/usr/sbin/mysqld(_Z11mysql_parseP3THDPcjP12Parser_state+0x32f)[0x6df27f]
/usr/sbin/mysqld(_Z16dispatch_command19enum_server_commandP3THDPcj+0x1407)[0x6e0777]
/usr/sbin/mysqld(_Z24do_handle_one_connectionP3THD+0xcf)[0x6ad6ff]
/usr/sbin/mysqld(handle_one_connection+0x47)[0x6ad827]
/usr/sbin/mysqld(pfs_spawn_thread+0x12a)[0x9549ba]
/lib64/libpthread.so.0[0x3cb6207851]
/lib64/libc.so.6(clone+0x6d)[0x3cb5ee890d]
```

**Comment by Charles-Kaminski** [comment]
Hi Y-Ken,  I reported the error via email.  I included all those test cases and hex so that the error could be isolated to the c++ function and put inside of code-blocks or some other IDE with the intention of feeding it the right hex use case and debugging the output.  We worked around the issue  by base64 encoding in a different layer in the solution stack.  I'll find some time to take a look again but I may not get to it before someone else.

**Comment by y-ken** [comment]
Thank you. I'm awaiting to hear good news.

**Comment by silvioster** [comment]
Heys!
Just wanted to let you know - you're using a signed char for "current" character.
Which means utf8 and other 8bit things will not encode properly as they'll clip and miss the lookup table.
Change it to unsigned (it'll warn about mismatch, ignore) - and all will be good.

**Comment by silvioster** [comment]
To check, try encoding a 8bit string, like a long fffffffffffffffffffff. It'll clip and give you noise as output.
So just change 
"const char *current;"
 to 
"const unsigned char *current;"

**Comment by y-ken** [comment]
Hi @Charles-Kaminski and @silvioster 

I'm sorry for staying a long time. I have fixed the code from char to unsigned char.
Could you please try it on again?

**Comment by silvioster** [comment]
Hi!
Thanks for notice!
It's a trivial fix, so don't think there's much to verify, already applied
fix when writing issue :)

But thanks anyway!

**Comment by y-ken** [comment]
@silvioster 

Thank you for checking! Closing this issue.
